version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/express-install
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/home/node/node-app:rw
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    container_name: database
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    command: [--auth]
    networks:
      - node-network

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: NGINX
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: mrquangkhai98@gmail.com
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - node-app
    volumes:
      - ./NGINX/nginx_secrets:/etc/letsencrypt
      - ./NGINX/user_conf.d:/etc/nginx/user_conf.d
    networks:
      - express-install-frontend_shared-network

volumes:
  dbdata:

networks:
  express-install-frontend_shared-network:
    external: true
